#!/usr/bin/env python3
"""drawio-libs: starts the draw.io flatpak with the icon libraries from the settings file loaded.

Run `drawio-libs install` once to set it up; see README.md.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from drawio_libs.cli import main  # noqa: E402

sys.exit(main(sys.argv[1:]))
